[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.67.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# [context.production]
#   command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://io-oi.netlify.com/*"
  to = "https://io-oi.me/:splat"
  force = true